% Create_W0.m
% This script generates an initial wasp invasion matrix for a spatial 
%  cluster of interest by sampling randomly based on observed wasp nests 
%  per unit area and a set of wasp population parameters 
% ========================================================================
%{
  The initial wasp invasion matrix is W0, with dimensions nc x nr 
   representing the number of grid cells on the map and the number of 
   stochastic runs respectively. 
  The parameter values used here were generated by a genetic algorithm in 
   Wasp_GA_script.m, but they could be estimated using other methods 
   depending on data available..
               * Written by O.J. Cacho (2021)
  ========================================================================
%}
clear;
path(path, '.\Data\');
% ------------------------- Load base data for desired cluster: 
% VIC cluster:
 load base_data_vic;
 f_out = 'W0_prm_vic';
% NSW cluster:
% load base_data_nsw;
% f_out = 'W0_prm_nsw';

% -------------------------- Create random matrix of wasp parameters 
nruns = 100;
rng('default');
nrows = size(wp_mat, 1); % number of paranmater sets in the matrix
wp_rand = unidrnd(20,[nruns,1]); % set of random indexes for wp rows
wp_samp = wp_mat(wp_rand,:); % sample of paramaters to use in runs
% -------------------------- Create random matrix of wasp parameters 
ng = length(garea);
W0 = zeros(ng,nruns); % matrix of initial population
for i = 1 : nruns
    i
    Kw = Disp_Kernel(wp_samp(i,3), D); %
    w_init = Solve_W0(obs_km2,wp_samp(i,4),hh_dens); % estimated initial population
    w0 = w_init;
    for j = 1:3 % arbitrary spread steps
        w0 = Rand_Spread(w0, Kw); % take one random step
    end
    W0(:,i) = w0;
end 
%
save(f_out, 'prm', 'W0', 'D', 'hh_dens', 'garea', 'gmap', 'gpoly', 'wp_mat', 'wp_samp')
%
